[package]
name = "kgi-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
kaspa-consensus-core.workspace = true
kgi-api-model = { path = "../kgi-api-model" }
kgi-core = { path = "../kgi-core" }
kgi-model = { path = "../kgi-model" }
moka.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
testcontainers-modules.workspace = true

[lints]
workspace = true
